---
password: ENC[AES256_GCM,data:E2YVbDEENczMYg==,iv:wzpM5yuHGyVjCsqQYLXfHldBRH/rfhXDPEvFxQfuOUk=,tag:zgfKagjbiZgeDIBvbi4Z2g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2026-02-18T09:22:00Z'
          enc: AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgE0TUoG43F7kMy6ABhqyYxWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdgwVWER9u6u7Lu7IAgEQgDvcBThmvztIDwQsybf6rcAVAzR0Hrk33hqRgzn8A+/g+g1f7IYKHv/OGrCkgnLOpvdHCWEF+I2z3acYrg==
          aws_profile: personal
    lastmodified: '2026-02-18T09:26:21Z'
    mac: ENC[AES256_GCM,data:E9X3BQ3dYRNMGPnjEMiYn9BGj5Fj4Ule2DXRXtdT1TLHBYGr2yVxIg2/yCTUIYumIy6raVo6jh+xk48LEqyIgypkt9Ty/zjQ6Ay70RRPPN7F3vaM0gI45algt6CspkaZDb1+jFDU8Q7JmxVpdy/trzuC31WrMmvt5APQLMahOgs=,iv:gv8GjgoXpO2ub0LAkXSkjxZSNwkmuZv3rfh3tmVNv3I=,tag:yb3e4eAjtEc8kKHdSOEiww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
