---
paperless_api_key: ENC[AES256_GCM,data:Hechiuw4gOFE5J2KxIjVa5urXngihg5ywXhnk6Qyu4zKFBECh8kPgA==,iv:crGgP5/Fpoqun61UDSJ3o9aDhBg1V8rJ0So/vBLVPgg=,tag:dar0eWTtKEVv5s2TN5EH7g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2026-01-17T11:54:07Z'
          enc: AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgH8rkLUAe/vaU10ltGlRpS3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFNobICcokwIBKeBDAgEQgDtSc8inNn8+9Nf8VGzV2GouTefV8IYM+cNHH1Fx4DBTg9LkqKHgN0y3Gi7kfvFqz9zU1hNjI/NCT5t7pw==
          aws_profile: personal
    lastmodified: '2026-01-17T15:58:24Z'
    mac: ENC[AES256_GCM,data:A1OrJLQu++5xv4o0Q9mPYklwkupkZ67SdZCNrIKXLlwErtFUiB6MNLdkdfUWs3+AX06OVLpEgtwWs+OAOI52D7HifrUU0jRlPoPpxFTAodeHG7/Bo9twojhibnDJ0zC7XJ/S+UrY6V+Hn8lkZPe+138N0qplhcgCVvdcKgBfh0k=,iv:PvxucBFW8nMEI62WjXgGVn/9rE0qIDZwEwhvLt0RXeI=,tag:KmU7Y01E2jkM01y+L3j9Vg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
