---
paperless_admin_password: ENC[AES256_GCM,data:47VWB0cjJPcZpvkyyewXgVMqwuy6yyTNfPlPyWyXt1X+,iv:ggZ8wNUb4JmxqbW0rOg8Onh+e+C784w6ocoqAWiE+o8=,tag:ByChP1u9UVmwHKCKU958vQ==,type:str]
paperless_secret_key: ENC[AES256_GCM,data:ERyo+Mo0nNtGnZK6En3WZVtEi/UwYHIUYshczlvN2X+V,iv:r7BIUB13FJGOAi2QUtLsCXTXAN8iiSYdAhBSbMEomzc=,tag:yCe9DjiCmGooD1WxqyYDDw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2026-01-17T11:54:07Z'
          enc: AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgH8rkLUAe/vaU10ltGlRpS3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFNobICcokwIBKeBDAgEQgDtSc8inNn8+9Nf8VGzV2GouTefV8IYM+cNHH1Fx4DBTg9LkqKHgN0y3Gi7kfvFqz9zU1hNjI/NCT5t7pw==
          aws_profile: personal
    lastmodified: '2026-01-17T11:54:07Z'
    mac: ENC[AES256_GCM,data:Ow5/wkI54NH6fsfZ8bMgBwAJKq30d0qeTqFm1EYY0WIRHXh6iA8AVJDuAokoGRxQ8AM1dmEhb+X1faleisvi1poa9ShX2LQjxdDI2QgfvIffIgi8ZB1uEXC9il5t/P5jBM/rOmUW+mi9DPy4ZoRPTpED2wCuaDuGDcSbFQcnqPw=,iv:xKWXwsjWPdV9Fvik4yR4r9HKsrOBAOCRjX6fjG4guFA=,tag:BdFgeb4uVmHpMHTIrhqoZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
